# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: UseDotNet@2
  displayName: 'Use DotNet'
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview6-012264'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'SharpShell\\SharpShell.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: GitHubPagesPublish@1
  displayName: 'Publish to GitHub Pages'
  inputs:
    docPath: '$(build.artifactstagingdirectory)\\SharpShell\\SharpShell\\dist\\*'
    githubusername: 'berserkerdotnet'
    githubemail: 'berserkerdotnet@gmail.com'
    githubaccesstoken: '$(GitHubToken)'
    repositoryname: 'SharpShell'
    branchname: 'gh-pages'
    commitmessage: 'Automated Release $(Release.ReleaseId)'
